services:
  explorer:
    image: ghcr.io/community-network/explorer-rust/explorer:latest
    restart: always
    environment:
      - DATABASE_URL={{MYSQL_DB_URL}}
      - MONGO_DETAILS_STRING={{MONGO_DETAILS_STRING}}
      - API_MAIN_ACCOUNT={{API_MAIN_ACCOUNT}}
      - API_MAIN_ACCOUNT_PASSWORD={{API_MAIN_ACCOUNT_PASSWORD}}
    healthcheck:
      test: curl -fk http://localhost:3030/ || exit 1
      interval: "60s"
      timeout: "3s"
      retries: 3
      start_period: "5s"